### PR TITLE
Add HD capable button

### PR DESCRIPTION
**Pull request by heroesiiifan**
- added HD buttons
- added psd for these buttons (you can translate all of them)
- restructured (depend submod) to avoid hundreds copied files

@misiokles

### CODE REVIEW

**Comment by misiokles** [comment]
Merged! But I wonder maybe these .psd files should be moved to mooders-tools-pack?

**Comment by heroesiiifan** [comment]
@GeorgeK1ng @Fabrice-TIERCELIN @altiereslima @XCOM-HUB @lishaoxia1985
Maybe someone of you want to also translate them in your language

Example how to: https://github.com/vcmi-mods/german-translation/tree/vcmi-1.6/mods/german-translation-theme
Help is here: https://github.com/vcmi-mods/h3-themes/blob/vcmi-1.6/h3-themes/misc/icon_x4_psd/_info.txt

> But I wonder maybe these .psd files should be moved to mooders-tools-pack?

Not sure what's better.

**Comment by GeorgeK1ng** [comment]
WoW! Now I just need someone who generate from your PSDs localized PNGs. I really like that idea, to overwrite buttons in any theme with custom ones from translation!

**Comment by heroesiiifan** [comment]
Can you provide a translation table?
Files needed: 
- https://github.com/vcmi-mods/h3-themes/tree/vcmi-1.6/h3-themes/mods/_Support/mods/OriginalButtons/content/sprites4x/images
- https://github.com/vcmi-mods/h3-themes/tree/vcmi-1.6/h3-themes/mods/_Support/mods/OriginalButtons/content/data4x

**Comment by GeorgeK1ng** [comment]
Thanks a lot! Here is translated text for localized buttons.

```
NEW GAME = NOVÁ HRA
LOAD GAME = NAHRÁT HRU
HIGHSCORE = NEJVYŠŠÍ SKÓRE
CREDITS = AUTOŘI
BACK = ZPĚT

SINGLEPLAYER = SAMOSTATNÝ SCÉNÁŘ (multiline)
MULTIPLAYER = HRA VÍCE HRÁČŮ (multiline)
CAMPAIGN = KAMPAŇ
TUTORIAL = VÝUKA
QUIT = ODEJÍT

CUSTOM = VLASTNÍ
```

I think we can now use localized campaings buttons as submod aswell.

```
RESTORATION OF ERATHIA = OBNOVA ERATHIE
ARMAGEDDON'S BLADE = MEČ ZKÁZY
SHADOW OF DEATH = STÍN SMRTI
HORN OF THE ABYSS = ROH PROPASTI
IN THE WAKE OF GODS = VE STOPÁCH BOHŮ
HEROES CHRONICLES = KRONIKY HRDINŮ
```

This how it was done previously. 

Initial screen
image

New game screen
image

Campaign screen
image

**Comment by altiereslima** [comment]
Portuguese:

NEW GAME = NOVO JOGO
LOAD GAME = CARREGAR JOGO
HIGHSCORE = MELHORES PONTUAÇÕES
CREDITS = CRÉDITOS
QUIT = SAIR

SINGLE SCENARIO = CENÁRIO ÚNICO
MULTI-PLAYER = MULTI-JOGADOR
CAMPAIGN = CAMPANHA
TUTORIAL = TUTORIAL
BACK = VOLTAR

SHADOW OF DEATH = SOMBRA DA MORTE
RESTORATION OF ERATHIA = RESTAURAÇÃO DE ERATHIA
ARMAGEDDON'S BLADE = LÂMINA DO ARMAGEDOM
CUSTOM = PERSONALIZAR

HORN OF THE ABYSS = CHIFRE DO ABISMO
IN THE WAKE OF GODS = NO RASTRO DOS DEUSES
HEROES CHRONICLES = CRÔNICAS DOS HERÓIS

**Comment by heroesiiifan** [comment]
Will have a look on the Weekend.

**Comment by XCOM-HUB** [comment]
Swedish (language="sv_SE"):

NEW GAME = NYTT SPEL
LOAD GAME = LADDA SPEL
HIGHSCORE = POÄNGLISTA
CREDITS = ERKÄNNANDE
QUIT = AVSLUTA

SINGLE SCENARIO = ENSKILT SCENARIO
MULTI-PLAYER = FLERSPELARSPEL
CAMPAIGN = KAMPANJ
TUTORIAL = HANDLEDNING
BACK = TILLBAKA

SHADOW OF DEATH = DÖDENS SKUGGA
RESTORATION OF ERATHIA = ÅTERUPPRÄTTANDET AV ERATHIA
ARMAGEDDON'S BLADE = HARMAGEDDONS KLINGA
CUSTOM = EGET

HORN OF THE ABYSS = AVGRUNDENS HORN
IN THE WAKE OF GODS = I GUDARS KÖLVATTEN
HEROES CHRONICLES = HJÄLTARNAS KRÖNIKOR

**Comment by misiokles** [comment]
Polish:

NEW GAME = NOWA GRA
LOAD GAME = WCZYTAJ GRĘ
HIGHSCORE = NAJLEPSZE WYNIKI
CREDITS = AUTORZY
QUIT = WYJDŹ

SINGLE SCENARIO = POJEDYNCZY SCENARIUSZ
MULTI-PLAYER = GRA WIELO OSOBOWA

CAMPAIGN = KAMPANIA
TUTORIAL = TRENING
BACK = WRÓĆ

SHADOW OF DEATH = CIEŃ ŚMIERCI
RESTORATION OF ERATHIA = ODRODZENIE ERATHII
ARMAGEDDON'S BLADE = OSTRZE ARMAGEDONU
CUSTOM = WŁASNA

HORN OF THE ABYSS = RÓG OTCHŁANI
IN THE WAKE OF GODS = PRZEBUDZENIE BOGÓW
HEROES CHRONICLES = HEROES KRONIKI

**Comment by Olegmods** [comment]
Russian (probably different from OH3 localisations due to them being many, I tried to use the best terminology I can):

NEW GAME = НОВАЯ ИГРА
LOAD GAME = ЗАГРУЗИТЬ ИГРУ
HIGHSCORE = РЕКОРДЫ
CREDITS = СОЗДАТЕЛИ
QUIT = ВЫХОД

SINGLE SCENARIO = ОДИНОЧНАЯ ИГРА
MULTI-PLAYER = МУЛЬТИПЛЕЕР
CAMPAIGN = КАМПАНИЯ
TUTORIAL = ОБУЧЕНИЕ
BACK = НАЗАД

SHADOW OF DEATH = ТЕНЬ СМЕРТИ
RESTORATION OF ERATHIA = ВОЗРОЖДЕНИЕ ЭРАФИИ
ARMAGEDDON'S BLADE = КЛИНОК АРМАГЕДДОНА
CUSTOM = ВЫБРАТЬ

HORN OF THE ABYSS = РОГ БЕЗДНЫ
IN THE WAKE OF GODS = ВО ИМЯ БОГОВ
HEROES CHRONICLES = ХРОНИКИ ГЕРОЕВ

**Comment by heroesiiifan** [comment]
Done :)

**Comment by XCOM-HUB** [comment]
The 4 vertical buttons inside HIGHSCORE are not translated. Have you made any attempt to translate them like you did with the other buttons? I only need to translate 2 of the buttons (CAMPAIGN and RESET).
CAMPAIGN = KAMPANJ
RESET = NOLLSTÄLL
STANDARD = STANDARD
EXIT = EXIT
HIGHSCORE

PS: I also wonder why Rank, Player, Land, and Days aren't translated for me. They should be translated.

**Comment by GeorgeK1ng** [comment]
@heroesiiifan Can you please add missing Heroes Chronicles images to Original Buttons?
https://github.com/vcmi-mods/h3-themes/tree/vcmi-1.6/h3-themes/mods/_Support/mods/OriginalButtons/content/sprites/images

**Comment by heroesiiifan** [comment]
> @heroesiiifan Can you please add missing Heroes Chronicles images to Original Buttons? https://github.com/vcmi-mods/h3-themes/tree/vcmi-1.6/h3-themes/mods/_Support/mods/OriginalButtons/content/sprites/images

Done with #17
(They was already existing in x4 - so i've only downscaled them).

**Comment by heroesiiifan** [comment]
> Have you made any attempt to translate them like you did with the other buttons?

No. Not yet. In german these buttons already existed in german RoE. It's only a problem for languages without any official translation. Maybe I'll try it in future. But I think there are much more untranslated buttons.

> PS: I also wonder why Rank, Player, Land, and Days aren't translated for me. They should be translated.

They should be translated. Otherwise something is wrong with translation JSON file.

**Comment by XCOM-HUB** [comment]
> They should be translated. Otherwise something is wrong with translation JSON file.

I will complete the Swedish translation soon. Hopefully, this will be fixed, otherwise I will have to find the faulty strings and correct them.

**Comment by heroesiiifan** [comment]
> I will complete the Swedish translation soon. Hopefully, this will be fixed, otherwise I will have to find the faulty strings and correct them.

German is working just fine. So it seems there is something wrong/missing in swedish translation.

**Pull request merged**
